### ISSUE TITLE
VSO CI, fail on unittest failure

### ISSUE THREAD

**Issue by ornatwork** [deloitte-solvas/SlackerRunner#12]
Make sure it fails on test failure.  Orn needs edit permission to make that happen at VSO slackerrunner ci

**Comment by jdshkolnik** [comment]
@ornatwork Why should it fail on test failure? You just want to make sure it doesn't deploy if it's a partial success, right?

**Comment by ornatwork** [comment]
No, I wan't it to fail on UnittTest failure so I notice when there is a problem,  I had numerous builds last week that had problems that I didn't notice because there was no failure.

Anyway I fixed it already.
