### ISSUE TITLE
VS2015 test Explorer shows green success icon when first success is returned even while still running

### ISSUE THREAD

**Issue by jdshkolnik** [deloitte-solvas/SlackerRunner#3]
If a Slacker spec has more than one test, the icon reflects the first success reported which is a bit misleading because it can still bomb on another test. Until completely finished, it should either continue displaying the green "play" icon.

![image](https://cloud.githubusercontent.com/assets/2047520/15437735/c63ae16c-1e96-11e6-911a-3e03aaecff3a.png)

**Comment by ornatwork** [comment]
After analyzing how it works in VS, there is nothing I can do about it.  This is a normal VS behavior, VS shows tests green until they fail, the top indicator shows that the test is still running which means it hasn't completed.  The code below duplicates this nicely and runs until the 95th iteration then fails.

    [TestMethod]
    public void TestMethod1()
    {
      for (int i = 0; i < 100; i++)
      {
        Console.WriteLine("the count=" + i);
        Thread.Sleep(100);
        if (i == 95)
          throw new AssertFailedException();
      }
    }

**Comment by ornatwork** [comment]
The play icon turns into checkmark with normal tests, but not with Slacker... slacker tests turn into checkmark on the first pass within the test group

**Comment by ornatwork** [comment]
Better test to examine the same behavior.

    [Fact]
    public void TestMethod1()
    {
      for (int i = 0; i < 100; i++)
      {
        Console.WriteLine("the count=" + i);
        Thread.Sleep(100);
      }
    }

**Comment by ornatwork** [comment]
The individual test execution #9 takes care of this, you can still run in a group with the limitations listed here.
