### ISSUE TITLE
Create CI

### ISSUE THREAD

**Issue by ornatwork** [deloitte-solvas/SlackerRunner#7]
Created at 
https://ornatwork.visualstudio.com/SlackerRunner_CI/_build?_a=completed&definitionId=1

**Comment by ornatwork** [comment]
Badge and link added to readme
https://github.com/ornatwork/SlackerRunner/blob/master/README.md

**Comment by ornatwork** [comment]
Need to add auto update of Version, also auto upload to Nuget on success

**Comment by ornatwork** [comment]
Version and auto upload to Nuget has been implemented, CI moved to this location
https://solvas.visualstudio.com/Solvas/_build?_a=completed&definitionId=1

**Comment by jdshkolnik** [comment]
@ornatwork I moved the nuget.org publish step to the release definition triggered by the CI build you modified. I'm trying to maintain a clear differentiation between build and release.
